/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <sqlite3.h>
#include <Python.h>

#define DB "rebides.db"

int contagem;
	
static int callback(void *NotUsed, int argc, char **argv, char **azColName){
	int i;
	contagem = atoi( argv[0] ? argv[0] : "NULL");
	
	return 0;
}
  
/*******************************************************
	function responsable for counting totla number of techers
	in the higher edutation system per year
	
	iAno - year to be counted
	
	returns the number of teachers counted

*******************************************************/
PyObject* tnt_per_year(int iAno){
	// builds the query
	sqlite3 *db;  
	char *zErrMsg = 0;
	int rc;
	
	char* cQuery = "SELECT COUNT(*) FROM docentes WHERE ano =";
	//strcat(cQuery, (char*) itoa(iAno, cQuery, 10 ));
	
	printf("Query:%s\n", cQuery);

	// opens the database
	rc = sqlite3_open(DB, &db);

	// executes the query aleady built
	rc = sqlite3_exec(db, cQuery, callback, 0, &zErrMsg);
	if( rc!=SQLITE_OK ){
		fprintf(stderr, "SQL error: %s\n", zErrMsg);
		sqlite3_free(zErrMsg);
	}
	sqlite3_close(db);
	
	// returns the total teachers found in the query
	return PyInt_FromLong(contagem);
}
