/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <sqlite3.h>
#include <string.h>
#include <Python.h>
#include <malloc.h>

#include "functions.h"

#define MAX_QUERY 512

/*******************************************************
	Add total number of teachers in the higher 
	education system per year to file
*******************************************************/
void count_teachers_to_file(){
	char* cHeader = (char *) malloc(MAX_QUERY);
	char* cCounter = (char *) malloc(MAX_QUERY);
	PyObject* poList;
	int i;
	int iCounter;
	
	// add header to file
	strcpy(cHeader, "list of holders of a degree per year");
	generate_list_header(cHeader);
	
	// add list to file
	for (i = 0; i < 10; i++)
	{
		// add year header
		generate_year_header(i);
	
		// get counter
		sprintf(cCounter, "%d\n", PyInt_AsLong(count_teachers(i)));
		
		// append counter to list
		append_string_to_file(cCounter);
	}
	
	// free memory previously allocated
	free(cCounter);
	free(cHeader);
}

/*******************************************************
	Add total number of teachers per 
	establishment and per year to file
*******************************************************/
void count_teachers_per_establishment_to_file(){
	char* cHeader = (char *) malloc(MAX_QUERY);
	PyObject* poList;
	int i;
	
	// add header to file
	strcpy(cHeader, "total number of teachers per establishment and per year");
	generate_list_header(cHeader);
	
	// add list to file
	for (i = 0; i < 10; i++)
	{
		// add year header
		generate_year_header(i);
	
		// get list
		poList = count_teachers_per_establishment(i);
		
		// write list to file
		write_list_to_file(poList);
	}
	
	// free memory previously allocated
	free(cHeader);
}

/*******************************************************
	Add total number of teachers per degree and per year to file
*******************************************************/
void count_teachers_per_degree_to_file(){
	char* cHeader = (char *) malloc(MAX_QUERY);
	PyObject* poList;
	int i;
	
	// add header to file
	strcpy(cHeader, "total number of teachers per degree and per year");
	generate_list_header(cHeader);
	
	// add list to file
	for (i = 0; i < 10; i++)
	{
		// add year header
		generate_year_header(i);
	
		// get list
		poList = count_teachers_per_degree(i);
		
		// write list to file
		write_list_to_file(poList);
	}
	
	// free memory previously allocated
	free(cHeader);
}

/*******************************************************
	Add total number of teachers per degree, 
	per establishment and per year to file
*******************************************************/
void count_teachers_per_degree_establishment_to_file(){
	char* cHeader = (char *) malloc(MAX_QUERY);
	PyObject* poList;
	int i;
	
	// add header to file
	strcpy(cHeader, \
		"total number of teachers per degree, per establishment and per year");
	generate_list_header(cHeader);
	
	// add list to file
	for (i = 0; i < 10; i++)
	{
		// add year header
		generate_year_header(i);
	
		// get list
		poList = count_teachers_per_degree_establishment(i);
		
		// write list to file
		write_list_to_file(poList);
	}
	
	// free memory previously allocated
	free(cHeader);
}

/*******************************************************
	Add list of establishments per year to file
*******************************************************/
void list_establishments_per_year_to_file(){
	char* cHeader = (char *) malloc(MAX_QUERY);
	PyObject* poList;
	int i;
	
	// add header to file
	strcpy(cHeader, "list of establishments per year");
	generate_list_header(cHeader);
	
	// add list to file
	for (i = 0; i < 10; i++)
	{
		// add year header
		generate_year_header(i);
	
		// get list
		poList = list_establishments_per_year(i);
		
		// write list to file
		write_list_to_file(poList);
	}
	
	// free memory previously allocated
	free(cHeader);
}

/*******************************************************
	Add list of holders of a degree per year to file
*******************************************************/
void list_teachers_per_degree_year_to_file(){
	char* cHeader = (char *) malloc(MAX_QUERY);
	PyObject* poList;
	int i;
	
	// add header to file
	strcpy(cHeader, "list of holders of a degree per year");
	generate_list_header(cHeader);
	
	// add list to file
	for (i = 0; i < 10; i++)
	{
		// add year header
		generate_year_header(i);
	
		// get list
		poList = list_teachers_per_degree_year(i);
		
		// write list to file
		write_list_to_file(poList);
	}
	
	// free memory previously allocated
	free(cHeader);
}


/*******************************************************
	Add list of personnel leaving the institution per year to file
*******************************************************/
void list_teachers_leaving_institution_year_to_file(){
	char* cHeader = (char *) malloc(MAX_QUERY);
	PyObject* poList;
	int i;
	
	// add header to file
	strcpy(cHeader, "list of personnel leaving the institution per year");
	generate_list_header(cHeader);
	
	// add list to file
	for (i = 0; i < 10; i++)
	{
		// add year header
		generate_year_header(i);
	
		// get list
		poList = list_teachers_leaving_institution_year(i);
		
		// write list to file
		write_list_to_file(poList);
	}
	
	// free memory previously allocated
	free(cHeader);
}

/*******************************************************
	Add list of new personnel in the institution per year to file
*******************************************************/
void list_new_teachers_institution_year_to_file(){
	char* cHeader = (char *) malloc(MAX_QUERY);
	PyObject* poList;
	int i;
	
	// add header to file
	strcpy(cHeader, "list of new personnel in the institution per year");
	generate_list_header(cHeader);
	
	// add list to file
	for (i = 0; i < 10; i++)
	{
		// add year header
		generate_year_header(i);
	
		// get list
		poList = list_new_teachers_institution_year(i);
		
		// write list to file
		write_list_to_file(poList);
	}
	
	// free memory previously allocated
	free(cHeader);
}