/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <sqlite3.h>
#include <string.h>
#include <Python.h>
#include <malloc.h>

#define DB "rebides.db"
#define MAX_QUERY 200

int contagem;
	
static int callback(void *NotUsed, int argc, char **argv, char **azColName){
	int i;
	contagem = atoi( argv[0] ? argv[0] : "NULL");
	
	return 0;
}
  
/*******************************************************

	Responsable for counting total number of teachers
	in the higher edutation system per year
	
		iAno - year to be counted
	
		returns the number of teachers counted

*******************************************************/
PyObject* count_teachers(int iAno){
	sqlite3 *db;  
	char *zErrMsg = 0;
	int rc;

	// declare local variables and allocate memory to them
	char* cQuery;
	char* cAno;
	
	cQuery = (char *) malloc(MAX_QUERY);
	cAno = (char *) malloc(sizeof(char));
	
	// builds the query
	strcpy(cQuery, "SELECT COUNT(DISTINCT id_docente) FROM fichas_docencia WHERE ano=");
	sprintf(cAno, "%d", iAno);			// converts year to string
	strcat(cQuery, cAno);	    // concatenate year to string

	// print the query for debugging purposes
	printf("Ano       :%s\n", cAno);
	printf("Query     :%s\n", cQuery);

	// opens the database
	rc = sqlite3_open(DB, &db);

	// executes the query aleady built
	rc = sqlite3_exec(db, cQuery, callback, 0, &zErrMsg);
	if( rc!=SQLITE_OK ){
		fprintf(stderr, "SQL error: %s\n", zErrMsg);
		sqlite3_free(zErrMsg);
	}
	
	// closes the database
	sqlite3_close(db);
	
	// free memory
	free(cQuery);
	free(cAno);
	
	// returns the total teachers found in the query
	return PyInt_FromLong(contagem);
}